# Generated by Django 4.2.7 on 2023-12-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Username', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=250)),
                ('Confirmpassword', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='MovieInfo',
        ),
    ]
